- name: Create default containers
  docker_container:
   name: "{{ default_container_name }}{{ item }}"
   image: "{{ default_container_image }}"
   command: "{{ default_container_command }}"
   state: present
  with_sequence: count={{ create_containers }}
